### ISSUE TITLE
Roadmap for Dorimanx kernel

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/Dorimanx-SG2-I9100-Kernel#81]
Changes planned:
- [x] Re-add UKMS and LMK changes 
- [x] Change ZRAM compression back to LZO, LZ4 always maxes out ZRAM with lower swappiness.
- [x] ~~Tweak ZRAM swappiness and other related settings~~ - Not required
- [x] ~~Update toolchain - Keep linaro, linaro is good~~ - Not required
- [x] ~~Update LMK thresholds to match android N configs. Dori G2 kernel is a lot more aggressive, and I think there's a lot of wasted CPU time on the S2 with same configs~~ - Not required
- [x] Update zzmoove with new profiles and changes
- [x] Disable zzmoove hotplugging from source rather than from script to prevent issues
- [x] ~~Sync updates from LineageOS git~~ -Mostly conflicting

**Comment by gsstudios** [comment]
I've done all of the necessary changes to be satisfied for public release :)
